#!/usr/bin/env python3
"""Emit per-module icon nudges measured from the icon font.

Nerd Font icons report a uniform advance width while their ink is wider and
varies per glyph, so Pango centres a box that does not match what is drawn and
each icon lands at a different offset. Measuring the ink at build time lets the
stylesheet compensate per module instead of guessing a single margin. A
control may also opt out of compensation entirely: naming it with an empty
nudge claims its glyphs without emitting a rule, so it renders at geometric
centre.
"""

import argparse
import pathlib
import re
import sys

import gi

gi.require_version("Pango", "1.0")
gi.require_version("PangoCairo", "1.0")

from gi.repository import Pango, PangoCairo  # noqa: E402  (after gi.require_version)

# Nerd Font glyphs live in the private use areas.
GLYPH = re.compile(r"[\ue000-\uf8ff\U000f0000-\U000ffffd]")

# A control opts out of its module's mean by naming itself. The name and the
# glyphs it covers are attributes of the same call, but they can sit either
# way round and any amount of tooltip text apart, so the name is found by
# scanning the call rather than by matching a fixed shape. An empty name
# opts out of compensation too: the glyphs are still claimed, so they join
# neither the mean nor a rule of their own.
NAMED = re.compile(r':nudge\s+"([^"]*)"')

HEADER = """// Generated by icon-metrics.py from the icon font's own metrics.
// Do not edit: rebuild the flake to regenerate.
"""


def ink_width(layout, glyph):
    """Distance from the pen to the right edge of the marks, in pixels.

    The left side bearing counts: a glyph whose ink starts inside its own
    advance is drawn that much further right than one that starts at the pen,
    even when the two paint the same width. Measuring from the pen rather than
    from the ink covers both.
    """
    layout.set_text(glyph, -1)
    ink, _logical = layout.get_pixel_extents()
    return ink.x + ink.width


def calls(source):
    """Yield (start, end) of every parenthesised call in the source.

    Glyphs belong to the call that draws them, which is what a name has to
    follow: a module file holds several controls, and one control's ladder of
    state glyphs says nothing about its neighbour's.
    """
    opens = []
    for index, character in enumerate(source):
        if character == "(":
            opens.append(index)
        elif character == ")" and opens:
            yield opens.pop(), index + 1


def groups(source):
    """Map each name to its glyphs, and return the module's unclaimed rest.

    The innermost name wins, so a named control inside a named one is measured
    on its own glyphs rather than counted twice.
    """
    named = {}
    claimed = set()
    # Innermost first, so a nested name claims its glyphs before the call
    # around it can.
    for start, end in sorted(calls(source), key=lambda span: span[1] - span[0]):
        block = source[start:end]
        name = NAMED.search(block)
        if not name:
            continue
        positions = {
            start + match.start() for match in GLYPH.finditer(block)
        } - claimed
        if not positions:
            continue
        claimed |= positions
        named.setdefault(name.group(1), []).extend(
            source[position] for position in positions
        )

    rest = [
        match.group() for match in GLYPH.finditer(source) if match.start() not in claimed
    ]
    return named, rest


def normalise(family):
    """Fontconfig matches loosely, so compare on letters and digits alone."""
    return "".join(c for c in family if c.isalnum()).casefold()


def check_font(font_map, context, description):
    """Fail loudly when the requested family is not what actually loaded.

    Pango silently substitutes a fallback, which would emit confident-looking
    nudges measured from the wrong font.
    """
    requested = description.get_family()
    resolved = font_map.load_font(context, description).describe().get_family()
    if normalise(requested) != normalise(resolved):
        raise SystemExit(f"icon-metrics: {requested} not available, got {resolved}")


def rule(selector, nudge):
    """One absolute declaration: the measured margin alone, no shared nudge."""
    return f"{selector} {{\n\tmargin-left: {nudge}px;\n}}\n"


def module_rules(layout, modules, cell):
    """Yield module rules, then the named icons that opt out of them.

    Named rules come last: they are no more specific than a module rule, so
    source order is what lets a named icon win. An empty name claims its
    glyphs from the mean but emits nothing, leaving the control at geometric
    centre.
    """
    named_rules = []

    def nudge_for(glyphs):
        # A control may swap glyphs by state, so compensate for their mean: no
        # single margin can centre every glyph in a ladder.
        widths = [ink_width(layout, glyph) for glyph in set(glyphs)]
        return round(cell - sum(widths) / len(widths))

    for path in sorted(modules.glob("*.yuck")):
        named, rest = groups(path.read_text(encoding="utf-8"))

        if rest:
            nudge = nudge_for(rest)
            if nudge:
                yield rule(f".{path.stem} .bar-icon", nudge)

        for name, glyphs in sorted(named.items()):
            if not name:
                continue
            nudge = nudge_for(glyphs)
            if nudge:
                named_rules.append(rule(f".bar-icon.nudge-{name}", nudge))

    yield from named_rules


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--family", required=True, help="icon font family")
    parser.add_argument("--size", required=True, type=float, help="icon size in pixels")
    parser.add_argument(
        "--cell",
        required=True,
        type=float,
        help="ink allowance the stylesheet reserves for an icon, in pixels",
    )
    parser.add_argument("modules", type=pathlib.Path, help="directory of module sources")
    args = parser.parse_args(argv)

    description = Pango.FontDescription(args.family)
    description.set_absolute_size(args.size * Pango.SCALE)

    font_map = PangoCairo.font_map_get_default()
    context = font_map.create_context()
    check_font(font_map, context, description)

    layout = Pango.Layout(context)
    layout.set_font_description(description)

    rules = list(module_rules(layout, args.modules, args.cell))
    if not rules:
        print("icon-metrics: no icons found; is the font available?", file=sys.stderr)
        return 1

    print(HEADER + "\n" + "\n".join(rules), end="")
    return 0


if __name__ == "__main__":
    sys.exit(main())
