#!/bin/sh
set -u

if [ "$#" -ne 0 ]; then
    printf 'usage: ui-clipboard\n' >&2
    exit 2
fi

config_home=${XDG_CONFIG_HOME:-${HOME:?HOME must be set}/.config}
cliphist=${UI_CLIPHIST:-cliphist}
desktop_theme=${UI_DESKTOP_THEME:-desktop-theme}
rofi=${UI_ROFI:-rofi}
wl_copy=${UI_WL_COPY:-wl-copy}
mode=$("$desktop_theme" get)
selection_file=$(mktemp --tmpdir ui-clipboard.XXXXXX)
trap 'rm -f -- "$selection_file"' 0

"$cliphist" list |
    "$rofi" \
        -dmenu \
        -p Clipboard \
        -monitor -1 \
        -theme "$config_home/rofi/themes/clipboard-$mode.rasi" \
        -no-custom > "$selection_file"

if [ ! -s "$selection_file" ]; then
    exit 0
fi

"$cliphist" decode < "$selection_file" | "$wl_copy"
