#!/bin/sh
set -u

if [ "$#" -eq 1 ] && [ "$1" = --help ]; then
    printf 'usage: ui-launcher\n'
    exit 0
fi

if [ "$#" -ne 0 ]; then
    printf 'usage: ui-launcher\n' >&2
    exit 2
fi

config_home=${XDG_CONFIG_HOME:-${HOME:?HOME must be set}/.config}
desktop_theme=${UI_DESKTOP_THEME:-desktop-theme}
rofi=${UI_ROFI:-rofi}
mode=$("$desktop_theme" get)
exec "$rofi" -show drun -monitor -1 -theme "$config_home/rofi/themes/launcher-$mode.rasi"
